# Generated by Django 3.0.1 on 2024-01-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classroom', models.IntegerField()),
                ('Faculty', models.CharField(max_length=200)),
                ('Sem', models.IntegerField()),
            ],
        ),
    ]
