# Generated by Django 4.2.3 on 2024-02-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_studentcount_teachercount_alter_class_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomNo', models.IntegerField()),
            ],
        ),
    ]
